array_horizontal_layout_threshold = "1000"
array_width = 100
array_layout = "Block"
chain_indent = "Block"
chain_one_line_max = "80"
closure_block_indent_threshold = 2
condense_wildcard_suffixes = true
control_style = "Legacy"
control_brace_style = "ClosingNextLine"
fn_args_density = "Compressed"
fn_return_indent = "WithWhereClause"
normalize_comments = true
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
